[2024-11-21T03:15:13.734+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-21T03:15:07.791783+00:00 [queued]>
[2024-11-21T03:15:13.741+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-21T03:15:07.791783+00:00 [queued]>
[2024-11-21T03:15:13.741+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-21T03:15:13.752+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-11-21 03:15:07.791783+00:00
[2024-11-21T03:15:13.758+0000] {standard_task_runner.py:57} INFO - Started process 66 to run task
[2024-11-21T03:15:13.761+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-11-21T03:15:07.791783+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpwfa5df4g']
[2024-11-21T03:15:13.763+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask s3_upload
[2024-11-21T03:15:13.801+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-21T03:15:07.791783+00:00 [running]> on host 8655590629ae
[2024-11-21T03:15:13.855+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T03:15:07.791783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T03:15:07.791783+00:00'
[2024-11-21T03:15:14.096+0000] {logging_mixin.py:151} INFO - Bucket create failed '[s3 bucket name]': Parameter validation failed:
Invalid bucket name "[s3 bucket name]": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2024-11-21T03:15:14.112+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
  File "/opt/airflow/etls/aws_etl.py", line 26, in upload_to_s3
    s3.put(file_path, bucket+'/raw/'+ s3_file_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 536, in _put
    trailing_sep(rpath) or await self._isdir(rpath)
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 1411, in _isdir
    return bool(await self._lsdir(path))
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 706, in _lsdir
    async for c in self._iterdir(
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 756, in _iterdir
    async for i in it:
  File "/home/airflow/.local/lib/python3.9/site-packages/aiobotocore/paginate.py", line 30, in __anext__
    response = await self._make_request(current_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/aiobotocore/client.py", line 329, in _make_api_call
    api_params = await self._emit_api_params(
  File "/home/airflow/.local/lib/python3.9/site-packages/aiobotocore/client.py", line 450, in _emit_api_params
    await self.meta.events.emit(
  File "/home/airflow/.local/lib/python3.9/site-packages/aiobotocore/hooks.py", line 66, in _emit
    response = await resolve_awaitable(handler(**kwargs))
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/handlers.py", line 284, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "[s3 bucket name]": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2024-11-21T03:15:14.131+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20241121T031507, start_date=20241121T031513, end_date=20241121T031514
[2024-11-21T03:15:14.143+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task s3_upload (Parameter validation failed:
Invalid bucket name "[s3 bucket name]": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"; 66)
[2024-11-21T03:15:14.173+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-21T03:15:14.186+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
